apiVersion: v1
kind: Service
metadata:
  namespace: service-ixcsoft
  name: service-ixcsoft
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: service-ixcsoft
