export const BULL_MQ_JOBS = {
  IXCSOFT: {
    CRON: {
      POLL_OPEN_INVOICES: 'IXCSOFT.CRON.POLL_OPEN_INVOICES',
    },
    POLL_INVOICES_FOR_APPLICATION: 'IXCSOFT.POLL_INVOICES_FOR_APPLICATION',
    PROCESS_INVOICE: 'IXCSOFT.PROCESS_INVOICE',
  },
} as const;
